on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-20.04
    steps:
      - run: date -Iseconds
      - run: env | sort
      - run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: windows
          goarch: amd64
          goversion: "1.17.2"
          project_path: "./cmd/actiontest"
          extra_files: README.md
          ldflags:
            "-X 'github.com/danbrakeley/actiontest/internal/buildvar.Version=${{ github.event.release.tag_name }}' -X
            'github.com/danbrakeley/actiontest/internal/buildvar.BuildTime=$(date -Iseconds)'"
